# 断言,如果断言失败，会报错，会抛出一个异常
# AssertionError
assert 1 == 1, '断言失败'
